use acxdb;

insert into adresse values
(1, 'France', 'Belfort','Avenue Jean Jaures','106B', null),
(2, 'France', 'Montbéliard', 'Place Ferrer', '10', 'appartement 3');

insert into representant values 
(1, 0765682315, 'john.doe@test.com', 'Doe', 'John', 2, 'Gérant');

insert into dossier values 
(1, 0381542219, 'contact@lacompta.fr', 'LaCompta', 'SELARL', 1,1, 130000, 1, 1, 'Société ayant en difficulté');

insert into utilisateur values
(1,'test@itfam.fr','Alpha','Testeur','TEST','3bsHYHMj4xyKyfPHP1NfPMYGF4SG2M5DX3VN9eEPRWdd'),
(2,'decouverte.acx@itfam.fr','passe','droit','NEW-CLIENT','jeTestAccountX.2023');

insert into compte values 
(null,1,'Comptes de capitaux',1,0),
(null,10,'Capital et réserves',1,0),
(null,101,'Capital',1,0),
(null,102,'Fonds fiduciaires',1,0),
(null,104,'Primes liées au capital social',1,0),
(null,105,'Écarts de réévaluation',1,0),
(null,106,'Réserves',1,0),
(null,1061,'Réserve légale',1,0),
(null,1062,'Réserves indisponibles',1,0),
(null,1063,'Réserves statutaires ou contractuelles',1,0),
(null,1064,'Réserves réglementées',1,0),
(null,1068,'Autres réserves',1,0),
(null,107,'Écart d’équivalence',1,0),
(null,108,'Compte de l’exploitant',1,0),
(null,109,'Actionnaires : Capital souscrit – non appelé',1,0),
(null,11,'Report à nouveau (solde créditeur ou débiteur)',1,0),
(null,12,'Résultat de l’exercice (bénéfice ou perte)',1,0),
(null,13,'Subventions d’investissement',1,0),
(null,131,'Subventions d’équipement',1,0),
(null,138,'Autres subventions d’investissement',1,0),
(null,139,'Subventions d’investissement inscrites au compte de résultat',1,0),
(null,1391,'Subventions d’équipement',1,0),
(null,1398,'Autres subventions d’investissement',1,0),
(null,14,'Provisions réglementées',1,0),
(null,142,'Provisions réglementées relatives aux immobilisations',1,0),
(null,143,'Provisions réglementées relatives aux stocks',1,0),
(null,144,'Provisions réglementées relatives aux autres éléments de l’actif',1,0),
(null,145,'Amortissements dérogatoires',1,0),
(null,146,'Provision spéciale de réévaluation',1,0),
(null,147,'Plus-values réinvesties',1,0),
(null,148,'Autres provisions réglementées',1,0),
(null,15,'Provisions',1,0),
(null,151,'Provisions pour risques',1,0),
(null,153,'Provisions pour pensions et obligations similaires',1,0),
(null,154,'Provisions pour restructurations',1,0),
(null,155,'Provisions pour impôts',1,0),
(null,156,'Provisions pour renouvellement des immobilisations',1,0),
(null,157,'Provisions pour charges à répartir sur plusieurs exercices',1,0),
(null,158,'Autres provisions pour charges',1,0),
(null,16,'Emprunts et dettes assimilées',1,0),
(null,161,'Emprunts obligataires convertibles',1,0),
(null,162,'Obligations représentatives de passifs nets remis en fiducie',1,0),
(null,163,'Autres emprunts obligataires',1,0),
(null,164,'Emprunts auprès des établissements de crédit',1,0),
(null,165,'Dépôts et cautionnements reçus',1,0),
(null,167,'Emprunts et dettes assortis de conditions particulières',1,0),
(null,1671,'Émissions de titres participatifs',1,0),
(null,1674,'Avances conditionnées de l’État',1,0),
(null,1675,'Emprunts participatifs',1,0),
(null,168,'Autres emprunts et dettes assimilées',1,0),
(null,169,'Primes de remboursement des obligations',1,0),
(null,17,'Dettes rattachées à des participations',1,0),
(null,171,'Dettes rattachées à des participations (groupe)',1,0),
(null,174,'Dettes rattachées à des participations (hors groupe)',1,0),
(null,178,'Dettes rattachées à des sociétés en participation',1,0),
(null,18,'Comptes de liaison des établissements et sociétés en participation',1,0),
(null,2,'Comptes d’immobilisations',1,0),
(null,20,'Immobilisations incorporelles',1,0),
(null,201,'Frais d’établissement',1,0),
(null,203,'Frais de recherche et de développement',1,0),
(null,205,'Concessions et droits similaires, brevets, licences, marques, procédés, logiciels…',1,0),
(null,206,'Droit au bail',1,0),
(null,207,'Fonds commercial',1,0),
(null,208,'Autres immobilisations incorporelles',1,0),
(null,2081,'Mali de fusion sur actifs incorporels',1,0),
(null,21,'Immobilisations corporelles',1,0),
(null,211,'Terrains',1,0),
(null,2111,'Terrains nus',1,0),
(null,2112,'Terrains aménagés',1,0),
(null,2113,'Sous-sols et sursols',1,0),
(null,2114,'Terrains de carrières',1,0),
(null,2115,'Terrains bâtis',1,0),
(null,2116,'Compte d’ordre sur immobilisations',1,0),
(null,212,'Agencements et aménagements de terrains',1,0),
(null,213,'Constructions',1,0),
(null,2131,'Bâtiments',1,0),
(null,2135,'Installations générales – agencements – aménagements des constructions',1,0),
(null,2138,'Ouvrages d’infrastructure',1,0),
(null,214,'Constructions sur sol d’autrui ',1,0),
(null,215,'Installations techniques, matériels et outillage industriels',1,0),
(null,2151,'Installations complexes spécialisées',1,0),
(null,2153,'Installations à caractère spécifique',1,0),
(null,2154,'Matériel industriel',1,0),
(null,2155,'Outillage industriel',1,0),
(null,2157,'Agencements et aménagements du matériel et outillage industriels',1,0),
(null,218,'Autres immobilisations corporelles',1,0),
(null,2181,'Installations générales, agencements, aménagements divers',1,0),
(null,2182,'Matériel de transport',1,0),
(null,2183,'Matériel de bureau et matériel informatique',1,0),
(null,2184,'Mobilier',1,0),
(null,2185,'Cheptel',1,0),
(null,2186,'Emballages récupérables',1,0),
(null,2187,'Mali de fusions sur actifs corporels',1,0),
(null,22,'Immobilisations mises en concession',1,0),
(null,23,'Immobilisations en cours',1,0),
(null,231,'Immobilisations corporelles en cours',1,0),
(null,232,'Immobilisations incorporelles en cours',1,0),
(null,237,'Avances et acomptes versés sur immobilisations incorporelles',1,0),
(null,238,'Avances et acomptes versés sur commandes d’immobilisations corporelles',1,0),
(null,2388,'Autres immobilisations corporelles',1,0),
(null,25,'Parts dans des entreprises liées et créances sur des entreprises liées',1,0),
(null,26,'Participations et créances rattachées à des participations',1,0),
(null,261,'Titres de participation',1,0),
(null,266,'Autres formes de participation',1,0),
(null,267,'Créances rattachées à des participations',1,0),
(null,268,'Créances rattachées à des sociétés en participation',1,0),
(null,269,'Versements restant à effectuer sur titres de participation non libérés',1,0),
(null,27,'Autres immobilisations financières',1,0),
(null,271,'Titres immobilisés autres que les TIAP',1,0),
(null,272,'Titres immobilisés (droit de créance)',1,0),
(null,273,'Titres immobilisés de l’activité de portefeuille',1,0),
(null,274,'Prêts',1,0),
(null,275,'Dépôts et cautionnements versés',1,0),
(null,276,'Autres créances immobilisées',1,0),
(null,277,'(Actions propres ou parts propres)',1,0),
(null,278,'Mali de fusion sur actifs financiers',1,0),
(null,279,'Versements restant à effectuer sur titres immobilisés non libérés',1,0),
(null,28,'Amortissements des immobilisations',1,0),
(null,280,'Amortissements des immobilisations incorporelles',1,0),
(null,2801,'Frais d’établissement ',1,0),
(null,2803,'Frais de recherche et de développement',1,0),
(null,2805,'Concessions et droits similaires, brevets, licences, logiciels…',1,0),
(null,2807,'Fonds commercial',1,0),
(null,2808,'Autres immobilisations incorporelles',1,0),
(null,28081,'Amortissements du mali de fusion sur actifs incorporels',1,0),
(null,281,'Amortissements des immobilisations corporelles',1,0),
(null,2812,'Agencements, aménagements de terrains',1,0),
(null,2813,'Constructions',1,0),
(null,2814,'Constructions sur sol d’autrui',1,0),
(null,2815,'Installations, matériel et outillage industriels',1,0),
(null,2818,'Autres immobilisations corporelles',1,0),
(null,28187,'Amortissement du mali de fusion sur actifs corporels',1,0),
(null,282,'Amortissements des immobilisations mises en concession',1,0),
(null,29,'Dépréciations des immobilisations',1,0),
(null,290,'Dépréciations des immobilisations incorporelles',1,0),
(null,2905,'Marques, procédés, droits et valeurs similaires',1,0),
(null,2906,'Droit au bail',1,0),
(null,2907,'Fonds commercial',1,0),
(null,2908,'Autres immobilisations incorporelles',1,0),
(null,29081,'Dépréciation du mali de fusion sur actifs incorporels',1,0),
(null,291,'Dépréciations des immobilisations corporelles',1,0),
(null,29187,'Dépréciation du mali de fusion sur actifs corporels',1,0),
(null,292,'Dépréciations des immobilisations mises en concession',1,0),
(null,293,'Dépréciations des immobilisations en cours',1,0),
(null,2931,'Immobilisations corporelles en cours',1,0),
(null,2932,'Immobilisations incorporelles en cours',1,0),
(null,296,'Dépréciations des participations et créances rattachées à des participations',1,0),
(null,2961,'Titres de participation',1,0),
(null,2966,'Autres formes de participation',1,0),
(null,2967,'Créances rattachées à des participations',1,0),
(null,2968,'Créances rattachées à des sociétés en participation',1,0),
(null,297,'Dépréciations des autres immobilisations financières',1,0),
(null,2971,'Titres immobilisés autre que TIAP – droit de propriété',1,0),
(null,2972,'Droit de créance ',1,0),
(null,2973,'Titres immobilisés de l’activité de portefeuille',1,0),
(null,2974,'Prêts ',1,0),
(null,2975,'Dépôts et cautionnements versés',1,0),
(null,2976,'Autres créances immobilisées ',1,0),
(null,29787,'Dépréciation du mali de fusion sur actifs financiers',1,0),
(null,3,'Comptes de stocks et en-cours',1,0),
(null,31,'Matières premières (et fournitures)',1,0),
(null,311,'Matières (ou groupe) A',1,0),
(null,312,'Matières (ou groupe) B',1,0),
(null,317,'Fournitures A, B, C,',1,0),
(null,32,'Autres approvisionnements',1,0),
(null,321,'Matières consommables',1,0),
(null,322,'Fournitures consommables',1,0),
(null,326,'Emballages',1,0),
(null,33,'En-cours de production de biens',1,0),
(null,331,'Produits en cours',1,0),
(null,335,'Travaux en cours',1,0),
(null,34,'En-cours de production de services',1,0),
(null,341,'Études en cours',1,0),
(null,345,'Prestations de services en cours',1,0),
(null,35,'Stocks de produits',1,0),
(null,351,'Produits intermédiaires',1,0),
(null,355,'Produits finis',1,0),
(null,358,'Produits résiduels (ou matières de récupération)',1,0),
(null,36,'Stocks provenant d’immobilisations',1,0),
(null,37,'Stocks de marchandises',1,0),
(null,38,'stocks en voie d’acheminement',1,0),
(null,39,'Dépréciations des stocks et en-cours',1,0),
(null,391,'Dépréciations des matières premières (et fournitures)',1,0),
(null,392,'Dépréciations des autres approvisionnements',1,0),
(null,393,'Dépréciations des en-cours de production de biens',1,0),
(null,394,'Dépréciations des en-cours de production de services',1,0),
(null,395,'Dépréciations des stocks de produits',1,0),
(null,397,'Dépréciations des stocks de marchandises',1,0),
(null,4,'Comptes de tiers',1,0),
(null,40,'Fournisseurs et comptes rattachés',1,0),
(null,400,'Fournisseurs et comptes rattachés',1,0),
(null,401,'Fournisseurs',1,0),
(null,403,'Fournisseurs – Effets à payer',1,0),
(null,404,'Fournisseurs d’immobilisations',1,0),
(null,405,'Fournisseurs d’immobilisations – Effets à payer',1,0),
(null,408,'Fournisseurs – Factures non parvenues',1,0),
(null,409,'Fournisseurs débiteurs',1,0),
(null,4091,'Fournisseurs – Avances et acomptes versés sur commandes',1,0),
(null,4096,'Fournisseurs – Créances pour emballages et matériel à rendre',1,0),
(null,4097,'Fournisseurs – Autres avoirs',1,0),
(null,4098,'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus',1,0),
(null,41,'Clients et comptes rattachés',1,0),
(null,410,'Clients et comptes rattachés',1,0),
(null,411,'Clients',1,0),
(null,413,'Clients – Effets à recevoir',1,0),
(null,416,'Clients douteux ou litigieux',1,0),
(null,418,'Clients – Produits non encore facturés',1,0),
(null,419,'Clients créditeurs',1,0),
(null,4191,'Clients – Avances et acomptes reçus sur commandes',1,0),
(null,4196,'Clients – Dettes sur emballages et matériels consignés',1,0),
(null,4197,'Clients – Autres avoirs',1,0),
(null,4198,'Rabais, remises, ristournes à accorder et autres avoirs à établir',1,0),
(null,42,'Personnel et comptes rattachés',1,0),
(null,421,'Personnel – Rémunérations dues',1,0),
(null,422,'Comités d’entreprises, d’établissement, …',1,0),
(null,424,'Participation des salariés aux résultats',1,0),
(null,425,'Personnel – Avances et acomptes',1,0),
(null,426,'Personnel – Dépôts',1,0),
(null,427,'Personnel – Oppositions',1,0),
(null,428,'Personnel – Charges à payer et produits à recevoir',1,0),
(null,43,'Sécurité sociale et autres organismes sociaux',1,0),
(null,431,'Sécurité sociale',1,0),
(null,437,'Autres organismes sociaux',1,0),
(null,438,'Organismes sociaux – Charges à payer et produits à recevoir',1,0),
(null,44,'État et autres collectivités publiques',1,0),
(null,441,'État – Subventions à recevoir',1,0),
(null,442,'État – Impôts et taxes recouvrables sur des tiers',1,0),
(null,443,'Opérations particulières avec l’État les collectivités publiques et organismes internationaux',1,0),
(null,4431,'Créances sur l’État dûe à la suppression du décalage d’un mois en matière de TVA',1,0),
(null,4438,'Intérêts courus sur créances figurant au 4431',1,0),
(null,444,'État – Impôts sur les bénéfices',1,0),
(null,445,'État – Taxes sur le chiffre d’affaires',1,0),
(null,4452,'TVA due intracommunautaire',1,0),
(null,4455,'Taxes sur le chiffre d’affaires à décaisser',1,0),
(null,4456,'Taxes sur le chiffre d’affaires déductibles',1,0),
(null,4457,'Taxes sur le chiffre d’affaires collectées par l’entreprise',1,0),
(null,4458,'Taxes sur le chiffre d’affaires à régulariser ou en attente',1,0),
(null,446,'Obligations cautionnées',1,0),
(null,447,'Autres impôts, taxes et versements assimilés',1,0),
(null,448,'État – Charges à payer et produits à recevoir',1,0),
(null,449,'Quotas d’émission à acquérir',1,0),
(null,45,'Groupe et associés',1,0),
(null,451,'Groupe',1,0),
(null,455,'Associés – Comptes courants',1,0),
(null,456,'Associés – Opérations sur le capital',1,0),
(null,457,'Associés – Dividendes à payer',1,0),
(null,458,'Associés – Opérations faites en commun et en GIE',1,0),
(null,46,'Débiteurs divers et créditeurs divers',1,0),
(null,47,'Comptes transitoires ou d’attente',1,0),
(null,471,'Comptes d’attente',1,0),
(null,472,'Comptes d’attente',1,0),
(null,473,'Comptes d’attente',1,0),
(null,474,'Comptes d’attente',1,0),
(null,475,'Comptes d’attente',1,0),
(null,476,'Différence de conversion – Actif',1,0),
(null,477,'Différences de conversion – Passif',1,0),
(null,478,'Autres comptes transitoires',1,0),
(null,4786,'Différences d’évaluation sur instruments de trésorerie – ACTIF',1,0),
(null,4787,'Différences d’évaluation sur instruments de trésorerie – PASSIF',1,0),
(null,48,'Comptes de régularisation',1,0),
(null,481,'Charges à répartir sur plusieurs exercices',1,0),
(null,486,'Charges constatées d’avance',1,0),
(null,487,'Produits constatés d’avance',1,0),
(null,488,'Comptes de répartition périodique des charges et des produits',1,0),
(null,49,'Dépréciations des comptes de tiers',1,0),
(null,491,'Dépréciations des comptes de clients',1,0),
(null,495,'Dépréciations des comptes du groupe et des associés',1,0),
(null,4951,'Comptes du groupe',1,0),
(null,4955,'Comptes courants des associés',1,0),
(null,4958,'Opérations faites en commun et en GIE',1,0),
(null,496,'Dépréciations des comptes de débiteurs divers',1,0),
(null,5,'Comptes financiers',1,0),
(null,50,'Valeurs mobilières de placement',1,0),
(null,501,'Parts dans des entreprises liées',1,0),
(null,502,'Actions propres',1,0),
(null,503,'Actions',1,0),
(null,504,'Autres titres conférant un droit de propriété',1,0),
(null,505,'Obligations et bons émis par la société et rachetés par elle',1,0),
(null,506,'Obligations',1,0),
(null,507,'Bons du Trésor et bons de caisse à court terme',1,0),
(null,508,'Autres valeurs mobilières de placement et autres créances assimilées',1,0),
(null,509,'Versements restant à effectuer sur valeurs mobilières de placement non libérées',1,0),
(null,51,'Banques, établissements financiers et assimilés',1,0),
(null,511,'Valeurs à l’encaissement',1,0),
(null,512,'Banques',1,0),
(null,514,'Chèques postaux',1,0),
(null,515,' Caisses  du Trésor et des établissements publics',1,0),
(null,516,'Sociétés de bourse',1,0),
(null,517,'Autres organismes financiers',1,0),
(null,518,'Intérêts courus',1,0),
(null,519,'Concours bancaires courants',1,0),
(null,52,'Instruments de trésorerie',1,0),
(null,53,'Caisse',1,0),
(null,531,'Caisse siège social',1,0),
(null,54,'Régies d’avance et accréditifs',1,0),
(null,58,'Virements internes',1,0),
(null,59,'Dépréciations des comptes financiers',1,0),
(null,590,'Dépréciations des valeurs mobilières de placement',1,0),
(null,5903,'Actions',1,0),
(null,5904,'Autres titres conférant un droit de propriété',1,0),
(null,5906,'Obligations',1,0),
(null,5908,'Autres valeurs mobilières de placement et créances assimilées',1,0),
(null,6,'Comptes de charges',1,0),
(null,60,'Achats (sauf 603)',1,0),
(null,601,'Achats stockés – Matières premières (et fournitures)',1,0),
(null,602,'Achats stockés – Autres approvisionnements',1,0),
(null,6021,'Matières consommables',1,0),
(null,6022,'Fournitures consommables',1,0),
(null,6026,'Emballages',1,0),
(null,604,'Achats d’études et prestations de services',1,0),
(null,605,'Achats de matériel, équipements et travaux',1,0),
(null,606,'Achats non stockés de matière et fournitures',1,0),
(null,607,'Achats de marchandises',1,0),
(null,608,'récapitulation des frais accessoires incorporés aux achats',1,0),
(null,609,'Rabais, remises et ristournes obtenus sur achats',1,0),
(null,603,'Variations des stocks (approvisionnements et marchandises)',1,0),
(null,6031,'Variation des stocks de matières premières (et fournitures)',1,0),
(null,6032,'Variation des stocks des autres approvisionnements',1,0),
(null,6037,'Variation des stocks de marchandises 61/62 – Autres charges externes',1,0),
(null,61,'Services extérieurs',1,0),
(null,611,'Sous-traitance générale',1,0),
(null,612,'Redevances de crédit-bail',1,0),
(null,6122,'Crédit-bail mobilier',1,0),
(null,6125,'Crédit-bail immobilier',1,0),
(null,613,'Locations',1,0),
(null,614,'Charges locatives et de copropriété',1,0),
(null,615,'Entretien et réparations',1,0),
(null,616,'Primes d’assurances',1,0),
(null,617,'Études et recherches',1,0),
(null,618,'Divers',1,0),
(null,619,'Rabais, remises et ristournes obtenus sur services extérieurs',1,0),
(null,62,'Autres services extérieurs',1,0),
(null,621,'Personnel extérieur à l’entreprise',1,0),
(null,622,'Rémunérations d’intermédiaires et honoraires',1,0),
(null,623,'Publicité, publications, relations publiques',1,0),
(null,624,'Transports de biens et transports collectifs du personnel',1,0),
(null,625,'Déplacements, missions et réceptions',1,0),
(null,626,'Frais postaux et de télécommunications',1,0),
(null,627,'Services bancaires et assimilés',1,0),
(null,628,'Divers',1,0),
(null,629,'Rabais, remises et ristournes obtenus sur autres services extérieurs',1,0),
(null,63,'Impôts, taxes et versements assimilés',1,0),
(null,631,'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)',1,0),
(null,633,'Impôts, taxes et versements assimilés sur rémunérations (autres organismes)',1,0),
(null,635,'Autres impôts, taxes et versements assimilés (administrations des impôts)',1,0),
(null,6358,'Autres droits',1,0),
(null,637,'Autres impôts, taxes et versements assimilés (autres organismes)',1,0),
(null,64,'Charges de personnel',1,0),
(null,641,'Rémunérations du personnel',1,0),
(null,644,'Rémunération du travail de l’exploitant',1,0),
(null,645,'Charges de sécurité sociale et de prévoyance',1,0),
(null,646,'Cotisations sociales personnelles de l’exploitant',1,0),
(null,647,'Autres charges sociales',1,0),
(null,648,'Autres charges de personnel',1,0),
(null,65,'Autres charges de gestion courante',1,0),
(null,651,'Redevances pour concessions, brevets, licences, marques, procédés, logiciels…',1,0),
(null,653,'Jetons de présence',1,0),
(null,654,'Pertes sur créances irrécouvrables',1,0),
(null,655,'Quote-part de résultat sur opérations faites en commun',1,0),
(null,656,'Pertes de change sur créances commerciales',1,0),
(null,658,'Charges diverses de gestion courante',1,0),
(null,66,'Charges financières',1,0),
(null,661,'Charges d’intérêts',1,0),
(null,664,'Pertes sur créances liées à des participations',1,0),
(null,665,'Escomptes accordés',1,0),
(null,666,'Pertes de change financières',1,0),
(null,667,'Charges nettes sur cessions de valeurs mobilières de placement',1,0),
(null,668,'Autres charges financières',1,0),
(null,67,'Charges exceptionnelles',1,0),
(null,671,'Charges exceptionnelles sur opérations de gestion',1,0),
(null,672,'charges sur exercices antérieurs',1,0),
(null,674,'Opérations de constitution ou liquidation des fiducies',1,0),
(null,675,'Valeurs comptables des éléments d’actif cédés',1,0),
(null,678,'Autres charges exceptionnelles',1,0),
(null,68,'Dotations aux amortissements, aux dépréciations et provisions',1,0),
(null,681,'Dotations aux amortissements, aux dépréciations et provisions – Charges d’exploitation',1,0),
(null,6811,'Dotations aux amortissements sur immobilisations incorporelles et corporelles',1,0),
(null,6812,'Dotations aux amortissements des charges d’exploitation à répartir',1,0),
(null,6815,'Dotations aux provisions d’exploitation',1,0),
(null,6816,'Dotations pour dépréciations des immobilisations incorporelles et corporelles',1,0),
(null,6817,'Dotations pour dépréciations des actifs circulants',1,0),
(null,686,'Dotations aux amortissements, aux dépréciations et provisions – Charges financières',1,0),
(null,6861,'Dotations aux amortissements des primes de remboursement des obligations',1,0),
(null,6865,'Dotations aux provisions financières',1,0),
(null,6866,'Dotations pour dépréciations des éléments financiers',1,0),
(null,6868,'Autres dotations',1,0),
(null,687,'Dotations aux amortissements, aux dépréciations et provisions – Charges exceptionnelles',1,0),
(null,6871,'Dotations aux amortissements exceptionnels des immobilisations',1,0),
(null,6872,'Dotations aux provisions réglementées (immobilisations)',1,0),
(null,6873,'Dotations aux provisions réglementées (stocks)',1,0),
(null,6874,'Dotations aux autres provisions réglementées',1,0),
(null,6875,'Dotations aux provisions exceptionnelles',1,0),
(null,6876,'Dotations pour dépréciations exceptionnelles',1,0),
(null,69,'Participation des salariés – Impôts sur les bénéfices et assimilés',1,0),
(null,691,'Participation des salariés aux résultats',1,0),
(null,695,'Impôts sur les bénéfices',1,0),
(null,696,'Suppléments d’impôt sur les sociétés liés aux distributions',1,0),
(null,698,'Intégration fiscale',1,0),
(null,6981,'Intégration fiscale – Charges',1,0),
(null,6989,'Intégration fiscale – Produits',1,0),
(null,699,'Produits – Reports en arrière des déficits',1,0),
(null,7,'Comptes de produits',1,0),
(null,70,'Ventes de produits fabriqués, prestations de services, marchandises',1,0),
(null,701,'Ventes de produits finis',1,0),
(null,702,'Ventes de produits intermédiaires',1,0),
(null,703,'Ventes de produits résiduels',1,0),
(null,704,'Travaux',1,0),
(null,7041,'Travaux de catégorie (ou activité) A',1,0),
(null,7042,'Travaux de catégorie (ou activité) B',1,0),
(null,705,'Études',1,0),
(null,706,'Prestations de services',1,0),
(null,707,'Ventes de marchandises',1,0),
(null,708,'Produits des activités annexes',1,0),
(null,709,'Rabais, remises et ristournes accordés par l’entreprise',1,0),
(null,71,'Production stockée (ou déstockage)',1,0),
(null,713,'Variation des stocks (en-cours de production, produits)',1,0),
(null,7133,'Variation des en-cours de production de biens',1,0),
(null,7134,'Variation des en-cours de production de services',1,0),
(null,7135,'Variation des stocks de produits',1,0),
(null,72,'Production immobilisée',1,0),
(null,721,'Immobilisations incorporelles',1,0),
(null,722,'Immobilisations corporelles',1,0),
(null,74,'Subventions d’exploitation',1,0),
(null,75,'Autres produits de gestion courante',1,0),
(null,751,'Redevances pour concessions, brevets, licences, marques, procédés, logiciels….',1,0),
(null,752,'Revenus des immeubles non affectés à des activités professionnelles',1,0),
(null,753,'Jetons de présence et rémunérations d’administrateurs, gérants,',1,0),
(null,754,'Ristournes perçues des coopératives (provenant des excédents)',1,0),
(null,755,'Quote-parts de résultat sur opérations faites en commun',1,0),
(null,756,'Gains de change sur créances commerciales',1,0),
(null,758,'Produits divers de gestion courante',1,0),
(null,76,'Produits financiers',1,0),
(null,761,'Produits de participations',1,0),
(null,762,'Produits des autres immobilisations financières',1,0),
(null,763,'Revenus des autres créances',1,0),
(null,764,'Revenus des valeurs mobilières de placement',1,0),
(null,765,'Escomptes obtenues',1,0),
(null,766,'Gains de change financiers',1,0),
(null,767,'Produits nets sur cessions de valeurs mobilières de placement',1,0),
(null,768,'Autres produits financiers',1,0),
(null,77,'Produits exceptionnels',1,0),
(null,771,'Produits exceptionnels sur opérations de gestion',1,0),
(null,772,'produits sur exercices antérieurs',1,0),
(null,774,'Opérations de constitution ou liquidation des fiducies',1,0),
(null,775,'Produits des cessions d’éléments d’actif',1,0),
(null,777,'Quote-part des subventions d’investissement virée au résultat de l’exercice',1,0),
(null,778,'Autres produits exceptionnels',1,0),
(null,78,'Reprises sur amortissements, dépréciations et provisions',1,0),
(null,781,'Reprises sur amortissements, dépréciations et provisions d exploitation',1,0),
(null,7811,'Reprises sur amortissements des immobilisations incorporelles et corporelles',1,0),
(null,7815,'Reprises sur provisions d’exploitation',1,0),
(null,7816,'Reprises sur dépréciations des immobilisations incorporelles et corporelles',1,0),
(null,7817,'Reprises sur dépréciations des actifs circulants',1,0),
(null,786,'Reprises sur provisions pour risques et dépréciations  financières',1,0),
(null,7865,'Reprises sur provisions financières',1,0),
(null,7866,'Reprises sur dépréciations des éléments financiers',1,0),
(null,787,'Reprises sur provisions et dépréciations exceptionnelles',1,0),
(null,7872,'Reprises sur provisions réglementées (immobilisations)',1,0),
(null,7873,'Reprises sur provisions réglementées (stocks)',1,0),
(null,7874,'Reprises sur autres provisions réglementées',1,0),
(null,7875,'Reprises sur provisions exceptionnelles',1,0),
(null,7876,'Reprises sur dépréciations exceptionnelles',1,0),
(null,79,'Transferts de charges',1,0),
(null,791,'Transferts de charges d’exploitation',1,0),
(null,796,'Transferts de charges financières',1,0),
(null,797,'Transferts de charges exceptionnelles',1,0),
(null,8,'Comptes spéciaux',1,0),
(null,80,'Engagements',1,0),
(null,801,'Engagements donnés par l’entité',1,0),
(null,802,'Engagements reçus par l’entité',1,0),
(null,809,'Contrepartie des engagements',1,0),
(null,88,'Résultat en instance d’affectation',1,0),
(null,89,'Bilan',1,0);
DELETE FROM compte WHERE LENGTH(numero_compte) <= 2;


insert into compte_auxiliaire values 
(null,192,'Divers Fournisseurs',1,0),
(null,204,'Divers Clients',2,0);